version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: "$DB_PASS"
    ports:
      - "5432:5432"

  minio:
    hostname: minio
    image: minio/minio
    command: server /export --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - /mnt/hdd/minio/data:/export
      - /mnt/hdd/minio/config:/root/.minio
    environment:
      MINIO_ROOT_USER: "MINIO_ROOT_USER"
      MINIO_ROOT_PASSWORD: "MINIO_ROOT_PASSWORD"

